# Generated by Django 4.0.4 on 2022-05-24 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('CategoryId', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('ItemId', models.AutoField(primary_key=True, serialize=False)),
                ('ItemName', models.CharField(max_length=150)),
                ('Category', models.CharField(max_length=150)),
                ('Quantity', models.PositiveSmallIntegerField()),
                ('Details', models.TextField()),
                ('AmazonLink', models.CharField(max_length=150)),
                ('InsertBy', models.CharField(max_length=42)),
                ('InsertDate', models.DateField()),
                ('LastUpdated', models.DateTimeField()),
            ],
        ),
    ]
