# Generated by Django 4.0.4 on 2022-06-14 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0005_alter_items_lastupdated'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='Barcode',
            field=models.ImageField(blank=True, upload_to='barcodes/'),
        ),
        migrations.AlterField(
            model_name='items',
            name='InsertDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
